repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff (check)
        entry: scripts/uvpy -m ruff check .
        language: system
        pass_filenames: false

      - id: black-check
        name: black (check)
        entry: scripts/uvpy -m black --check .
        language: system
        pass_filenames: false

      - id: mypy
        name: mypy (type-check)
        entry: scripts/uvpy -m mypy --config-file packages/worker/pyproject.toml packages/worker/src
        language: system
        pass_filenames: false

