name: Bug report
description: Report a problem to help us improve
labels: ['type/bug']
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue and expected behavior.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App version
      placeholder: e.g. 0.1.0, nightly
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
