// Generated by tools/generate-tokens.mjs. Do not edit.

export const generatedSpacingScale = {
  '2xs': '0.25rem',
  xs: '0.5rem',
  sm: '0.75rem',
  md: '1rem',
  lg: '1.25rem',
  xl: '1.5rem',
  '2xl': '2rem',
  '3xl': '3rem',
} as const;

export const generatedRadiusScale = {
  sm: 'var(--radius-sm)',
  md: 'var(--radius-md)',
  lg: 'var(--radius-lg)',
  xl: 'var(--radius-xl)',
  frame: 'var(--aideon-radius-frame)',
} as const;

export const generatedElevationScale = {
  shell: 'var(--aideon-elevation-shell)',
  panel: 'var(--aideon-elevation-panel)',
  frame: 'var(--aideon-elevation-frame)',
} as const;
