
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Namespaced + requestId-wrapped setup completion signal.
 * 
 * The registered command is concrete over `tauri::Wry` (the codegen seam
 * cannot collect a runtime-generic command); the generic `_inner` keeps the
 * behaviour testable under `MockRuntime`.
 */
async systemSetupComplete(request: IpcRequest<SetupCompletePayload>) : Promise<Result<IpcResponse<null>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("system_setup_complete", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped setup state query.
 */
async systemSetupState(request: IpcRequest<EmptyPayload>) : Promise<Result<IpcResponse<SetupFlags>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("system_setup_state", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped worker health command.
 */
async systemWorkerHealth(request: IpcRequest<EmptyPayload>) : Promise<Result<IpcResponse<WorkerHealth>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("system_worker_health", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped temporal state query.
 */
async chronaTemporalStateAt(request: IpcRequest<StateAtArgs>) : Promise<Result<IpcResponse<StateAtResult>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chrona_temporal_state_at", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped diff summary query.
 */
async chronaTemporalDiff(request: IpcRequest<DiffArgs>) : Promise<Result<IpcResponse<DiffSummary>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chrona_temporal_diff", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped commit application command.
 */
async chronaTemporalCommitChanges(request: IpcRequest<CommitChangesRequest>) : Promise<Result<IpcResponse<CommitChangesResponse>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chrona_temporal_commit_changes", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped commit list query.
 */
async chronaTemporalListCommits(request: IpcRequest<ListCommitsPayload>) : Promise<Result<IpcResponse<ListCommitsResponse>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chrona_temporal_list_commits", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped branch creation command.
 */
async chronaTemporalCreateBranch(request: IpcRequest<CreateBranchRequest>) : Promise<Result<IpcResponse<BranchInfo>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chrona_temporal_create_branch", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped branch list query.
 */
async chronaTemporalListBranches(request: IpcRequest<EmptyPayload>) : Promise<Result<IpcResponse<ListBranchesResponse>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chrona_temporal_list_branches", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped branch merge command.
 */
async chronaTemporalMergeBranches(request: IpcRequest<MergeRequest>) : Promise<Result<IpcResponse<MergeResponse>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chrona_temporal_merge_branches", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped topology delta query.
 */
async chronaTemporalTopologyDelta(request: IpcRequest<TopologyDeltaArgs>) : Promise<Result<IpcResponse<TopologyDeltaResult>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chrona_temporal_topology_delta", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped metamodel query.
 */
async praxisMetamodelGet(request: IpcRequest<EmptyPayload>) : Promise<Result<IpcResponse<MetaModelDocument>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("praxis_metamodel_get", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped canvas scene query.
 */
async praxisCanvasGetScene(request: IpcRequest<CanvasScenePayload>) : Promise<Result<IpcResponse<CanvasShape[]>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("praxis_canvas_get_scene", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped canvas layout load command.
 */
async praxisCanvasGetLayout(request: IpcRequest<CanvasLayoutGetRequest>) : Promise<Result<IpcResponse<CanvasLayoutSaveRequest | null>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("praxis_canvas_get_layout", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped canvas layout persistence command.
 */
async praxisCanvasSaveLayout(request: IpcRequest<CanvasLayoutSaveRequest>) : Promise<Result<IpcResponse<null>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("praxis_canvas_save_layout", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped graph layout load command.
 */
async praxisGraphLayoutGet(request: IpcRequest<GraphLayoutGetRequest>) : Promise<Result<IpcResponse<GraphLayoutSaveRequest | null>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("praxis_graph_layout_get", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped graph layout persistence command.
 */
async praxisGraphLayoutSave(request: IpcRequest<GraphLayoutSaveRequest>) : Promise<Result<IpcResponse<null>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("praxis_graph_layout_save", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async praxisArtefactExecuteGraph(request: IpcRequest<GraphViewDefinition>) : Promise<Result<IpcResponse<GraphViewModel>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("praxis_artefact_execute_graph", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async praxisArtefactExecuteCatalogue(request: IpcRequest<CatalogueViewDefinition>) : Promise<Result<IpcResponse<CatalogueViewModel>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("praxis_artefact_execute_catalogue", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async praxisArtefactExecuteMatrix(request: IpcRequest<MatrixViewDefinition>) : Promise<Result<IpcResponse<MatrixViewModel>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("praxis_artefact_execute_matrix", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async praxisArtefactExecuteChart(request: IpcRequest<ChartViewDefinition>) : Promise<Result<IpcResponse<ChartViewModel>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("praxis_artefact_execute_chart", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async praxisTaskApplyOperations(request: IpcRequest<ApplyOperationsPayload>) : Promise<Result<IpcResponse<OperationBatchResult>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("praxis_task_apply_operations", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async praxisScenarioList(request: IpcRequest<EmptyPayload>) : Promise<Result<IpcResponse<ScenarioSummary[]>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("praxis_scenario_list", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The registered command is concrete over `tauri::Wry` (the codegen seam
 * cannot collect a runtime-generic command); the generic `_inner` keeps the
 * behaviour testable under `MockRuntime`.
 */
async systemWindowOpen(request: IpcRequest<OpenWindowPayload>) : Promise<Result<IpcResponse<null>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("system_window_open", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped project list query.
 */
async workspaceProjectsList(request: IpcRequest<EmptyPayload>) : Promise<Result<IpcResponse<ProjectPayload[]>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_projects_list", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped template list query.
 */
async workspaceTemplatesList(request: IpcRequest<EmptyPayload>) : Promise<Result<IpcResponse<TemplatePayload[]>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_templates_list", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Namespaced + requestId-wrapped template save command.
 */
async workspaceTemplatesSave(request: IpcRequest<TemplatePayload>) : Promise<Result<IpcResponse<TemplatePayload>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_templates_save", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceCreate(request: IpcRequest<OpenWorkspacePayload>) : Promise<Result<IpcResponse<WorkspaceStatus>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_create", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceOpen(request: IpcRequest<OpenWorkspacePayload>) : Promise<Result<IpcResponse<WorkspaceStatus>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_open", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceStatus(request: IpcRequest<EmptyPayload>) : Promise<Result<IpcResponse<WorkspaceStatus>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_status", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async workspaceClose(request: IpcRequest<EmptyPayload>) : Promise<Result<IpcResponse<null>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_close", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rebuild the derived foundation runtime as accepted work ([ADR-0040]).
 * Returns an [`AcceptedJob`] immediately (never a blocking response); the
 * rebuild runs off-thread and publishes proof-carrying readiness when the
 * foundation projections complete. Read-write is withheld until then.
 */
async workspaceRebuild(request: IpcRequest<EmptyPayload>) : Promise<Result<IpcResponse<AcceptedJob>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_rebuild", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Author one `create-node` into the open workspace's canonical log
 * ([golden-journey] step 3). The node id is minted host-side; a session
 * actor self-declares on the first authoring of a fresh workspace.
 */
async workspaceAuthorNode(request: IpcRequest<AuthorNodePayload>) : Promise<Result<IpcResponse<NodeRecord>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_author_node", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the derived twin's projected nodes ([golden-journey] step 3 read-back).
 */
async workspaceNodes(request: IpcRequest<EmptyPayload>) : Promise<Result<IpcResponse<NodeRecord[]>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_nodes", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the seed metamodel's authorable entity types and their attributes —
 * the palette the renderer offers ([golden-journey] step 2). Read-only; needs
 * no open workspace since the metamodel is embedded at build time.
 */
async workspaceMetamodelTypes(request: IpcRequest<EmptyPayload>) : Promise<Result<IpcResponse<MetaTypeInfo[]>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_metamodel_types", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Author one **metamodel-validated** entity into the open workspace's canonical
 * log ([golden-journey] step 3). The write is checked against the seed
 * effective schema before any operation is appended; an invalid write returns
 * `VALIDATION_FAILED` and never enters the op log.
 */
async workspaceAuthorTypedNode(request: IpcRequest<AuthorTypedNodePayload>) : Promise<Result<IpcResponse<NodeRecord>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_author_typed_node", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Assert a slot value on a layer over a valid-time interval — a plan or actual
 * claim ([golden-journey] step 4). The value is validated against the
 * attribute's metamodel kind/enum before any operation is appended.
 */
async workspaceSetClaim(request: IpcRequest<SetClaimPayload>) : Promise<Result<IpcResponse<null>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_set_claim", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve the twin at a viewpoint — every entity with its slots' effective
 * values ([golden-journey] step 5).
 */
async workspaceStateAt(request: IpcRequest<Viewpoint>) : Promise<Result<IpcResponse<ResolvedEntity[]>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_state_at", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Compare the twin at two viewpoints, returning the slots whose resolved value
 * differs ([golden-journey] step 6).
 */
async workspaceDiff(request: IpcRequest<DiffPayload>) : Promise<Result<IpcResponse<PropertyDelta[]>, HostError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("workspace_diff", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async systemLoggingContext() : Promise<Result<LoggingContextDto, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("system_logging_context") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async systemMetricsSnapshot() : Promise<MetricsSnapshot> {
    return await TAURI_INVOKE("system_metrics_snapshot");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
workspaceLifecycleChanged: WorkspaceLifecycleEvent,
workspaceReadyReadWrite: WorkspaceReadinessEvent
}>({
workspaceLifecycleChanged: "workspace:lifecycle_changed",
workspaceReadyReadWrite: "workspace:ready_read_write"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * The acknowledgement a long-running command returns immediately
 * ([accepted-job-shape]). Acceptance is receipt, not durability.
 */
export type AcceptedJob = { runId: string; queueClass: WorkQueueClass; idempotencyKey: string; ledgerRef: string; acceptedAt: string }
export type ApplyOperationsPayload = { branch?: string | null; operations?: PraxisOperation[] }
/**
 * Payload for authoring one node: an optional declared type id.
 */
export type AuthorNodePayload = { typeId: string | null }
/**
 * Payload for authoring one typed entity: the domain type key plus a flat
 * string-valued attribute map (name, enum choices, …).
 */
export type AuthorTypedNodePayload = { typeId: string; props?: Partial<{ [key in string]: string }> }
export type BranchInfo = { name: string; head: string | null }
export type CanvasEdge = { id: string; source: string; target: string; label?: string | null; z?: number | null }
export type CanvasGroup = { id: string; name?: string | null; parentId?: string | null; z?: number | null }
export type CanvasLayoutGetRequest = { docId: string; asOf: string; scenario?: string | null; layer?: string | null }
export type CanvasLayoutSaveRequest = { docId: string; asOf: string; scenario?: string | null; layer?: string | null; nodes?: CanvasNode[]; edges?: CanvasEdge[]; groups?: CanvasGroup[] }
export type CanvasNode = { id: string; typeId: string; x: number; y: number; w: number; h: number; z?: number; label?: string | null; groupId?: string | null }
export type CanvasScenePayload = { asOf?: string | null }
export type CanvasShape = { id: string; typeId: string; x: number; y: number; w: number; h: number; label?: string | null }
export type CatalogueColumn = { id: string; label: string; type: CatalogueColumnType }
export type CatalogueColumnType = "string" | "number" | "boolean"
export type CatalogueRow = { id: string; values: Partial<{ [key in string]: JsonValue }> }
export type CatalogueViewDefinition = { id: string; name: string; kind: string; asOf: string; layer?: string | null; scenario?: string | null; confidence?: number | null; filters?: ViewFilters | null; columns?: CatalogueColumn[]; limit?: number | null }
export type CatalogueViewModel = { metadata: ViewMetadata; columns: CatalogueColumn[]; rows: CatalogueRow[] }
export type ChangeSet = { nodeCreates: NodeVersion[]; nodeUpdates: NodeVersion[]; nodeDeletes: NodeTombstone[]; edgeCreates: EdgeVersion[]; edgeUpdates: EdgeVersion[]; edgeDeletes: EdgeTombstone[] }
export type ChartKpiSummary = { value: number; units?: string | null; delta?: number | null; trend?: string | null }
export type ChartPoint = { label: string; value: number; timestamp?: string | null }
export type ChartSeries = { id: string; label: string; color?: string | null; points: ChartPoint[] }
export type ChartViewDefinition = { id: string; name: string; kind: string; asOf: string; chartType: string; measure: string; dimension?: string | null; layer?: string | null; scenario?: string | null; confidence?: number | null; filters?: ViewFilters | null }
export type ChartViewModel = { metadata: ViewMetadata; chartType: string; series: ChartSeries[]; kpi?: ChartKpiSummary | null }
export type CommitChangesRequest = { branch: string; parent: string | null; author: string | null; time: string | null; message: string; tags: string[]; changes: ChangeSet }
export type CommitChangesResponse = { id: string }
export type CommitRef = { id: string } | { branch: { branch: string; at: string | null } }
export type CommitSummary = { id: string; parents: string[]; branch: string; author: string | null; time: string | null; message: string; tags: string[]; changeCount: number }
export type CreateBranchRequest = { name: string; from: CommitRef | null }
export type DiffArgs = { from: CommitRef; to: CommitRef; scope: string | null }
/**
 * Payload for a two-viewpoint diff ([golden-journey] step 6, [ADR-0008]).
 */
export type DiffPayload = { before: Viewpoint; after: Viewpoint }
export type DiffSummary = { from: string; to: string; nodeAdds: number; nodeMods: number; nodeDels: number; edgeAdds: number; edgeMods: number; edgeDels: number }
export type DurationSummary = { count: number; total_ms: number }
export type EdgeTombstone = { from: string; to: string }
export type EdgeVersion = { id: string | null; from: string; to: string; type: string | null; directed: boolean | null; props: JsonValue | null }
/**
 * Payload used when a command requires a payload object but has no inputs.
 */
export type EmptyPayload = Record<string, never>
export type GraphEdgeView = { id?: string | null; from: string; to: string; type?: string | null; label?: string | null; props?: JsonValue | null }
export type GraphLayoutGetRequest = { docId: string; widgetId: string; asOf: string; scenario?: string | null; layer?: string | null }
export type GraphLayoutNode = { id: string; x: number; y: number }
export type GraphLayoutSaveRequest = { docId: string; widgetId: string; asOf: string; scenario?: string | null; layer?: string | null; nodes?: GraphLayoutNode[] }
export type GraphNodeView = { id: string; label: string; type?: string | null; position?: Position | null; props?: JsonValue | null }
export type GraphViewDefinition = { id: string; name: string; kind: string; asOf: string; layout?: string | null; layer?: string | null; scenario?: string | null; confidence?: number | null; filters?: ViewFilters | null; scope?: GraphViewScope | null }
export type GraphViewModel = { metadata: ViewMetadata; stats: ViewStats; nodes: GraphNodeView[]; edges: GraphEdgeView[] }
export type GraphViewScope = { rootIds?: string[] }
/**
 * Stable error envelope returned by host commands.
 * 
 * - `code` is a stable, machine-readable identifier (snake_case).
 * - `message` is user-facing and may change between releases.
 */
export type HostError = { code: string; message: string }
/**
 * The RFC-9457 Problem Detail carried over IPC ([error-envelope], [ADR-0016]).
 * `HostError` maps to this at the boundary, gaining the category, recovery
 * hint, and correlation id that let the renderer react generically.
 */
export type IpcError = { 
/**
 * Stable, non-dereferenceable problem URI (`aideon:problem/<kebab-code>`).
 */
type: string; code: string; title: string; detail: string; category: ProblemCategory; recovery: ProblemRecovery; correlationId: string; details: JsonValue }
/**
 * Canonical IPC request envelope.
 * 
 * Matches the host design doc contract:
 * `{ requestId: "uuid", traceparent?: string, payload: { ... } }`.
 * 
 * `traceparent` is W3C Trace Context transport metadata (ADR-0019). It is
 * optional: absent means no span context; present but invalid returns
 * `INVALID_TRACE_CONTEXT` without echoing the raw value.
 */
export type IpcRequest<T> = { requestId: string; traceparent?: string | null; payload: T }
/**
 * Canonical IPC response envelope.
 * 
 * Matches the host design doc contract:
 * `{ requestId, status, result?, error? }`.
 */
export type IpcResponse<T> = { requestId: string; status: string; result?: T | null; error?: IpcError | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * The M0 flat lifecycle state ([workspace-lifecycle]): write capability is
 * enabled only in `ready_read_write`. M0 deliberately does not name semantic
 * axes (effective schema, temporal) it cannot prove; those arrive as additive
 * sibling fields at M1/M2. M0 emits the states the rebuild path produces; the
 * `opening`/`closed` transitions on create/open/close are a follow-up (#291).
 */
export type LifecycleState = "rebuilding" | "ready_read_write" | "recovery_read_only"
export type ListBranchesResponse = { branches: BranchInfo[] }
export type ListCommitsPayload = { branch: string }
export type ListCommitsResponse = { commits: CommitSummary[] }
export type LoggingContextDto = { session_id: string; build_version: string; build_commit: string | null; platform_os: string; platform_arch: string }
export type MatrixAxis = { id: string; label: string }
export type MatrixCell = { rowId: string; columnId: string; state: MatrixCellState; strength?: number | null; value?: string | null }
export type MatrixCellState = "connected" | "missing"
export type MatrixViewDefinition = { id: string; name: string; kind: string; asOf: string; rowType: string; columnType: string; relationship?: string | null; layer?: string | null; scenario?: string | null; confidence?: number | null; filters?: ViewFilters | null }
export type MatrixViewModel = { metadata: ViewMetadata; rows: MatrixAxis[]; columns: MatrixAxis[]; cells: MatrixCell[] }
export type MergeConflict = { reference: string; kind: string; message: string }
export type MergeRequest = { source: string; target: string }
export type MergeResponse = { result: string | null; conflicts: MergeConflict[] | null }
export type MetaAttribute = { name: string; uuid?: string | null; type: MetaAttributeKind; required?: boolean; enum?: string[] }
/**
 * A host-facing metamodel attribute descriptor for an entity type.
 */
export type MetaAttributeInfo = { 
/**
 * The attribute name (e.g. `name`, `tier`).
 */
name: string; 
/**
 * Whether a valid write must carry it.
 */
required: boolean; 
/**
 * The closed enum choices, when the attribute is an enum; else empty.
 */
enumValues: string[] }
export type MetaAttributeKind = "string" | "text" | "number" | "boolean" | "enum" | "datetime" | "blob"
export type MetaAttributeRules = { string: MetaStringRule | null; text: MetaStringRule | null; enum: MetaEnumRule | null }
export type MetaEnumRule = { caseSensitive: boolean | null }
export type MetaModelDocument = { version: string; description: string | null; types: MetaType[]; relationships: MetaRelationship[]; validation: MetaValidationRules | null }
export type MetaMultiplicity = { from: string; to: string }
export type MetaRelationship = { id: string; uuid?: string | null; label: string | null; from: string[]; to: string[]; directed: boolean | null; multiplicity: MetaMultiplicity | null; attributes?: MetaAttribute[] }
export type MetaRelationshipValidation = { allowSelf: boolean | null; allowDuplicate: boolean | null }
export type MetaStringRule = { maxLength: number | null }
export type MetaType = { id: string; uuid?: string | null; label: string | null; category: string | null; extends: string | null; attributes?: MetaAttribute[]; effectTypes?: string[] | null }
/**
 * A host-facing metamodel entity type — the authorable palette the renderer
 * offers ([M1 build contract], step 2).
 */
export type MetaTypeInfo = { 
/**
 * The domain type key (e.g. `Application`).
 */
id: string; 
/**
 * A human label; falls back to the id.
 */
label: string; 
/**
 * The metamodel category (e.g. `Business`, `Application`).
 */
category: string | null; 
/**
 * The type's authorable attributes.
 */
attributes: MetaAttributeInfo[] }
export type MetaValidationRules = { attributes: MetaAttributeRules | null; relationships: Partial<{ [key in string]: MetaRelationshipValidation }> | null }
export type MetricsSnapshot = { command_failures: Partial<{ [key in string]: number }>; job_failures: Partial<{ [key in string]: number }>; command_durations: Partial<{ [key in string]: DurationSummary }>; job_durations: Partial<{ [key in string]: DurationSummary }> }
/**
 * A host-facing projected node — the derived twin listing entry.
 */
export type NodeRecord = { 
/**
 * The node id.
 */
nodeId: string; 
/**
 * The declared node type's storage symbol UUID, if any.
 */
typeId: string | null; 
/**
 * The metamodel domain type key (e.g. `Application`), resolved from the
 * symbol UUID via the registry; `None` for an untyped or unknown-symbol node.
 */
typeLabel: string | null; 
/**
 * Whether a tombstone has retired the node.
 */
tombstoned: boolean }
export type NodeTombstone = { id: string }
export type NodeVersion = { id: string; type: string | null; props: JsonValue | null }
export type OpenWindowPayload = { window: string }
/**
 * Payload for create/open: the host-resolved workspace root.
 */
export type OpenWorkspacePayload = { root: string }
export type OperationBatchResult = { accepted: boolean; message?: string | null; commitId?: string | null }
export type Position = { x: number; y: number }
export type PraxisOperation = { kind: "createNode"; node: TwinNode } | { kind: "updateNode"; node: TwinNode } | { kind: "deleteNode"; node_id: string } | { kind: "createEdge"; edge: TwinEdge } | { kind: "updateEdge"; edge: TwinEdge } | { kind: "deleteEdge"; edge_id: string }
/**
 * RFC-9457 problem category ([error-envelope]): the renderer reacts to the
 * category generically rather than hard-coding per-code knowledge ([ADR-0016]).
 */
export type ProblemCategory = "validation" | "permission" | "conflict" | "transient" | "internal"
/**
 * RFC-9457 machine-readable recovery hint.
 */
export type ProblemRecovery = "retry" | "reconcile" | "refresh" | "none" | "report"
export type ProjectPayload = { id: string; name: string; scenarios: ScenarioSummary[] }
/**
 * One slot whose resolved value differs between two viewpoints ([ADR-0008]:
 * a diff compares two viewpoints).
 */
export type PropertyDelta = { 
/**
 * The entity id.
 */
nodeId: string; 
/**
 * The metamodel domain type key, if known.
 */
typeLabel: string | null; 
/**
 * The attribute name.
 */
field: string; 
/**
 * The value resolved at the first viewpoint, if any.
 */
before: string | null; 
/**
 * The value resolved at the second viewpoint, if any.
 */
after: string | null }
/**
 * An entity with its slots resolved at a viewpoint.
 */
export type ResolvedEntity = { 
/**
 * The entity id.
 */
nodeId: string; 
/**
 * The metamodel domain type key, if known.
 */
typeLabel: string | null; 
/**
 * The entity's resolved slots at the viewpoint, ordered by attribute name.
 */
properties: ResolvedProperty[] }
/**
 * A single resolved slot value at a viewpoint — the winning fact after
 * interval, layer, and asserted-time selection ([M2 core]).
 */
export type ResolvedProperty = { 
/**
 * The attribute name (e.g. `lifecycle`), resolved from its symbol UUID.
 */
field: string; 
/**
 * The effective value's display form.
 */
value: string; 
/**
 * The layer the winning fact came from (`plan` / `actual`).
 */
layer: string }
export type ScenarioSummary = { id: string; name: string; branch: string; description?: string | null; updatedAt: string; isDefault?: boolean | null }
/**
 * Payload for asserting one plan/actual claim at a valid time ([golden-journey]
 * step 4).
 */
export type SetClaimPayload = { entityId: string; typeId: string; attribute: string; value: string; 
/**
 * `"plan"` or `"actual"`.
 */
layer: string; validFrom: number; validTo: number | null }
export type SetupCompletePayload = { task: string }
export type SetupFlags = { frontend: boolean; backend: boolean }
export type StateAtArgs = { asOf: CommitRef; scenario: string | null; confidence: number | null; layer?: string | null }
export type StateAtResult = { asOf: string; scenario: string | null; confidence: number | null; layer?: string | null; nodes: number; edges: number }
export type TemplatePayload = { id: string; documentId: string; name: string; description: string; widgets: TemplateWidgetPayload[] }
export type TemplateWidgetPayload = { id: string; title: string; size?: string | null; kind: string; view: JsonValue }
export type TopologyDeltaArgs = { from: CommitRef; to: CommitRef }
export type TopologyDeltaResult = { from: string; to: string; nodeAdds: number; nodeDels: number; edgeAdds: number; edgeDels: number }
export type TwinEdge = { id?: string | null; from: string; to: string; type?: string | null; directed?: boolean | null; props?: JsonValue | null }
export type TwinNode = { id: string; type?: string | null; props?: JsonValue | null }
export type ViewFilters = { nodeTypes?: string[] | null; edgeTypes?: string[] | null; tags?: string[] | null; search?: string | null }
export type ViewMetadata = { id: string; name: string; asOf: string; layer?: string | null; scenario?: string | null; fetchedAt: string; source: string }
export type ViewStats = { nodes: number; edges: number }
/**
 * A viewpoint: an `as_of` valid time and an ordered layer preference
 * (highest priority first).
 */
export type Viewpoint = { 
/**
 * The valid-time coordinate to resolve at.
 */
asOf: number; 
/**
 * The layer preference, highest priority first (e.g. `["actual","plan"]`).
 */
layers: string[] }
/**
 * The class of long-running work. M0 runs only `Rebuild`; the other Continuum
 * classes are deferred to M4 (variants are additive).
 */
export type WorkQueueClass = "rebuild"
/**
 * A lightweight host-owned worker health snapshot for IPC exposure.
 * 
 * This was previously sourced from the (now-removed) Mneme prototype; it is a
 * host-local type until the M0 storage rebuild provides a real health surface.
 */
export type WorkerHealth = { ok: boolean; timestamp_ms: number }
/**
 * `workspace.lifecycle.changed` payload — the state-transition announcement.
 */
export type WorkspaceLifecycleEvent = { workspaceId: string; state: LifecycleState; jobId: string | null; errorCode: string | null; correlationId: string }
/**
 * `workspace.ready_read_write` payload — proof-carrying readiness ([ADR-0040]):
 * an integrity claim with the foundation hash attached, not a status message.
 */
export type WorkspaceReadinessEvent = { workspaceId: string; jobId: string; readiness: string; foundationRebuildHash: string; runtimeGeneration: string; correlationId: string }
/**
 * A host-facing summary of an open workspace's foundation state.
 */
export type WorkspaceStatus = { 
/**
 * The portable container identity.
 */
workspaceId: string; 
/**
 * The workspace's sole partition.
 */
partitionId: string; 
/**
 * On-disk format version.
 */
workspaceFormatVersion: number; 
/**
 * Count of applied canonical operations.
 */
appliedOpCount: number; 
/**
 * The structural foundation-rebuild hash over the current state.
 */
foundationRebuildHash: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
