[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aideon-worker"
version = "0.1.0"
description = "Aideon Praxis Python worker sidecar (RPC only)"
requires-python = ">=3.11"
dependencies = []
license = { file = "LICENSE" }

[project.optional-dependencies]
dev = [
  "ruff>=0.6",
  "black>=24.4",
  "pytest>=8.0",
  "pytest-cov>=5.0",
  "mypy>=1.10",
  "bandit>=1.7",
  "vulture>=2.11",
]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = [
  # Base
  "E", "F", "I",
  # Bugbear and upgrades
  "B", "UP",
  # Comprehensions & simplify
  "C4", "SIM",
  # Security (Bandit-like)
  "S",
  # Pylint conventions subset
  "PL",
  # Naming
  "N",
  # Commented code
  "ERA",
  # Docstring style
  "D",
]
ignore = []

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"packages/worker/tests/**" = ["D100", "D103", "S101"]

[tool.mypy]
python_version = "3.11"
packages = ["aideon_worker"]
strict = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_optional = true
explicit_package_bases = false
pretty = true

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
