[package]
name = "aideon-host"
version = "0.0.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
tauri = { version = "2" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
tauri-build = { version = "2" }

[dev-dependencies]
