#!/usr/bin/env node
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const version = process.argv[2];
if (!version) {
  console.error('usage: inject-version <version>');
  process.exit(2);
}

// JS/Electron preload
const appVersionFile = path.resolve(__dirname, '..', 'app/desktop/src/version.ts');
writeFileSync(
  appVersionFile,
  `// generated by semantic-release\nexport const version = '${version}';\n`,
);

console.log('Injected version', version);
