#!/usr/bin/env node
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const version = process.argv[2];
if (!version) {
  console.error('usage: inject-version <version>');
  process.exit(2);
}

// JS/Electron preload
const appVersionFile = path.resolve(__dirname, '..', 'packages/app/src/version.ts');
writeFileSync(
  appVersionFile,
  `// generated by semantic-release\nexport const version = '${version}';\n`,
);

// Python worker
const workerVersionFile = path.resolve(
  __dirname,
  '..',
  'packages/worker/src/aideon_worker/_version.py',
);
writeFileSync(workerVersionFile, `__all__ = ["__version__"]\n__version__ = "${version}"\n`);

console.log('Injected version', version);
