name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  js:
    name: JS Lint + Typecheck + Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
      - run: corepack enable || true
      - run: yarn --version
      - run: yarn install --frozen-lockfile
      - name: Commitlint PR title (non-blocking for Dependabot)
        if: ${{ github.event_name == 'pull_request' }}
        uses: wagoid/commitlint-github-action@v6
        continue-on-error: ${{ github.actor == 'dependabot[bot]' || startsWith(github.head_ref || '', 'dependabot/') }}
        with:
          configFile: commitlint.config.cjs
      - name: Commitlint commits on push (non-blocking for Dependabot)
        if: ${{ github.event_name == 'push' }}
        uses: wagoid/commitlint-github-action@v6
        continue-on-error: ${{ github.actor == 'dependabot[bot]' || startsWith(github.ref_name || '', 'dependabot/') }}
        with:
          configFile: commitlint.config.cjs
      - name: Prettier check
        run: yarn format:check
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test

  python:
    name: Python Lint + Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest
      - name: Lint (ruff)
        run: ruff check packages/worker || true
      - name: Format check (black)
        run: black --check packages/worker || true
      - name: Tests
        run: pytest -q packages/worker || true

  release:
    name: Semantic Release
    needs: [js, python]
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
      - run: corepack enable || true
      - run: yarn install --frozen-lockfile
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
