name: Package Artifacts

on:
  release:
    types: [published]

jobs:
  package:
    name: Build Installers (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '20'
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - run: corepack enable || true
      - name: Install dependencies
        run: yarn install --frozen-lockfile || npm ci
      - name: Build worker binary (PyInstaller)
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pyinstaller -F -n aideon-worker -p packages/worker/src packages/worker/src/aideon_worker/cli.py
          mkdir -p packages/app/extra/worker
          if [[ "$RUNNER_OS" == "Windows" ]]; then cp dist/aideon-worker.exe packages/app/extra/worker/; else cp dist/aideon-worker packages/app/extra/worker/; fi
      - name: Build app code
        run: yarn workspace @aideon/app build
      - name: Package with electron-builder
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: 'true'
        run: |
          VERSION=${{ github.event.release.tag_name }}
          npx electron-builder --projectDir packages/app \
            -c packages/app/electron-builder.yml \
            -c.extraMetadata.version=${VERSION} \
            --publish always

  worker:
    name: Build & Attach Worker Dists
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install build ruff black pytest
      - name: Lint
        run: ruff check packages/worker
      - name: Format check
        run: black --check packages/worker
      - name: Tests
        run: pytest -q packages/worker
      - name: Build dists
        working-directory: packages/worker
        run: python -m build
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packages/worker/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
