name: python-ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: latest

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Sync toolchain (uv)
        run: uv sync --all-groups --python 3.13

      - name: Lint (ruff + black --check)
        run: |
          scripts/uvpy -m ruff check .
          scripts/uvpy -m black --check .

      - name: Type check (mypy)
        run: scripts/uvpy -m mypy --config-file packages/worker/pyproject.toml packages/worker/src

      - name: Security (bandit)
        run: scripts/uvpy -m bandit -r packages/worker/src -x packages/worker/tests

      - name: Tests
        run: scripts/uvpy -m pytest -q packages/worker --cov=packages/worker/src --cov-report=xml:packages/worker/coverage.xml --cov-report=term

