name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Build and Publish Tauri Bundles
    uses: ./.github/workflows/reusable-release.yml
    with:
      publish: true
      os-matrix: '["ubuntu-latest","macos-latest","windows-latest"]'
