name: SonarCloud (Node/TS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: corepack enable || true
      - run: yarn install --frozen-lockfile || npm ci
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_NODE }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.sources=.
            -Dsonar.exclusions=**/dist/**,**/build/**,**/out/**,**/.yarn/**,**/node_modules/**,packages/worker/**
